#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the nonDivisibleSubset function below.
def nonDivisibleSubset(k, S):
    freq_list = [0]*k

    for number in S:
        freq_list[number%k] += 1

    count = min(freq_list[0], 1)
    for i in range(1, k//2 + 1):
        if (i != (k - i)):
            count += max(freq_list[i], freq_list[k - i])
    if (k%2 == 0):
        count += min(freq_list[k//2], 1)

    return count
